spring:
  cache:
    type: redis
    cache-names:
      - product_id_cache
      - product_list_cache
    redis:
      time-to-live: 60000
      cache-null-values: false

  redis:
    host: localhost
    port: 6379