spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: joechan1520@gmail.com
    password: kurxiuddwcanuufx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true