spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[1]:
        id: discovery-server-resources
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
      routes[2]:
        id: booking-service
        uri: http://localhost:8082
        predicates[0]: Path=/api/booking/**
        filters[0]: JwtAuthenticationFilter
      routes[3]:
        id: identity-service
        uri: http://localhost:8081
        predicates[0]: Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka